tradepost:
  api_key: "your_api_key_here"

interactive_brokers:
  account: "your_ib_account_number"
  host: "127.0.0.1"
  port: 7497  # Use 7497 for TWS paper trading, 4002 for IB Gateway paper trading
  client_id: 1

trading:
  cash_buffer: 50  # Buffer in USD/EUR for transaction costs